---
title: "Meer weten?"
---

## Praktijkgerichte publicaties

### Keynote Lambert Schuwirth: Programmatisch toetsen, een hype of logische ontwikkeling?

Op 6 december 2022 gaf Lambert Schuwirt (hoogleraar Medisch Onderwijs, Flinders University, Australie) een keynote bij de Toets-2-daagse georganiseerd door het Versnellingsplan Onderwijsinnovatie met ICT. In zijn keynote gaat Lambert in op de ontwikkelingen in de geneeskunde en het geneeskundeonderwijs, hoe programmatisch toetsen probeert belangrijke problemen met traditioneel toetsen te omzeilen, en hoe het beter aansluit bij huidige opvattingen over wat belangrijk is voor medische professionals.

[Keynote](https://www.youtube.com/watch?v=SfLerMRgYBA&list=PLWHj64yM9YGPWNgygTtnsdi88dMVs_ZsL&index=6)

### Programmatisch toetsen als motor voor professioneel leren in het hoger onderwijs 

In het boek Toetsrevolutie (2018) schreven Cees van der Vleuten, Suzanne Schut en Sylvia Heeneman het hoofdstuk “Programmatisch toetsen als motor voor professioneel leren in het hoger onderwijs" (p. 124-135). In dit hoofdstuk beschrijven zij op toegankelijke wijze wat programmatisch toetsen is en hoe het een bijdrage zou kunnen leveren aan meer professioneel leren binnen het hoger onderwijs.  

[Toetsrevolutie: Naar een feedbackcultuur in het hoger onderwijs](https://drive.google.com/file/d/1vjQ4hYdSMaMeu26lymvDNMKxKIRU7BSy/view?usp=share_link)

### ‘Wat is programmatisch toetsen?’ in 2 minuten 

In deze (Nederlands ondertitelde) animatie wordt in twee minuten uitgelegd wat programmatisch toetsen is. De animatie is ontwikkeld door Cees van der Vleuten. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/yhjzsNuVFmI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Drie perspectieven op toetsing: waar staat u en waar wilt u naar toe? 

In dit webinar (17 november 2022) gaat Cees van der Vleuten in op de drie perspectieven binnen toetsing: assessment of learning, assessment for learning en een meer systeem-geïntegreerde aanpak van toetsing. Cees daagt de kijker uit na te denken over de vraag: waar staat u nu en waar wilt u naar toe?  

Dit webinar is opgenomen voor de online leeromgeving. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/0AzX_QXl3N4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### In gesprek over veelgestelde vragen over programmatisch toetsen 

Op 6 juli 2020 vond een Q&A plaats waarin Cees van der Vleuten, Liesbeth Baartman en Tamara van Schilt-Mol antwoorden gaven op veelgestelde vragen over programmatisch toetsen. Tijdens deze Q&A wordt er onder meer gesproken over de uitgangspunten van programmatisch toetsen, de relatie met andere onderwijsconcepten en onderwijsinnovaties, en over het ontwerpen, implementeren en uitvoeren van programmatisch toetsen. 

Bekijk de Q&A [hier](https://video.han.nl/P2G/Player/Player.aspx?id=cCjdDl).

### Programmatischtoetsen.nl  

Op deze website vind je informatie over programmatisch toetsen en portretten van opleidingen die zijn aangesloten bij het Landelijk Netwerk Programmatisch toetsen. Daarnaast worden antwoorden gegeven op veel gestelde vragen over programmatisch toetsen. 

[Programmatisch toetsen – Platform Leren van Toetsen](https://lerenvantoetsen.nl/programmatisch-toetsen/)

### Curriculumperspectief op motivatie 

De manier waarop toetsing binnen een curriculum ingericht is, kan een groot effect hebben op de motivatie van studenten. In dit artikel wordt ingegaan op deze relatie. Er zijn zowel een praktijkgericht artikel als een wetenschappelijk artikel over dit onderwerp toegevoegd. 

[Praktijkgericht artikel: Een curriculumperspectief op motivatie](https://link.springer.com/article/10.1007/s10734-021-00699-3)

@kickert2022curricular

### Keynote van Liesbeth Baartman over de 6 principes van programmatisch toetsen

In deze kennisclip gaat bijzonder lector Toetsing en Beoordeling in beroepsonderwijs aan de Hogeschool Utrecht Liesbeth Baartman dieper in op de zes principes van programmatisch toetsen.

<iframe width="560" height="315" src="https://www.youtube.com/embed/fBCnwJUR1jI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Wetenschappelijke publicaties 

### Assessing professional competence: from methods to programmes 

De auteurs tonen met een model voor bepalen van bruikbaarheid van beoordelingsmethoden aan dat keuze van beoordelingsmethoden contextafhankelijk is en beoordelen een onderwijskundig ontwerpprobleem.

@van2005assessing

### The assessment of professional competence: building blocks for theory development

In dit artikel wordt onderscheid gemaakt tussen bestaande beoordelingstechnieken voor beoordelen van 'knows', knowing how' en 'showing how' en recente ontwikkelingen in beoordelingen op ‘does’-niveau.

@van2010assessment 

### Twelve Tips for programmatic assessment 

Dit artikel biedt twaalf concrete tips om programmatisch toetsen in de praktijk te ontwerpen. De auteurs hopen dat je hiermee zo ver als mogelijk kunt komen in jullie eigen praktijk. 

@doi:10.3109/0142159X.2014.973388

### A model for programmatic assessment fit for purpose 

De auteurs beschrijven een model voor programmatisch toetsen, dat tegelijkertijd de beoordeling voor leren en de beoordeling voor besluitvorming over de voortgang van de leerling optimaliseert. 

@van2012model 

### Programmatic assessment: From assessment of learning to assessment for learning 

Het doel van dit artikel is om verdere routes te beschrijven voor de ontwikkeling van programmatisch toetsen in de context van assessment for learning. 

@doi:10.3109/0142159X.2011.565828

### Ottawa 2020 consensus statement for programmatic assessment - 1. Agreement on the principles 

@heeneman2021ottawa

Dit artikel bestaat uit twee delen. In het eerste deel wordt ingegaan op de principes. In het tweede deel over hoe deze vorm krijgen in de praktijk. Het tweede deel is [hier](https://drive.google.com/file/d/1lIkm3Q6npUxjibh0VHq6RZnQCnUMQNoh/view?usp=share_link) te vinden.

### Where the rubber meets the road — An integrative review of programmatic assessment in health care professions education 

Dit artikel bevat een review dat werd uitgevoerd om de resultaten te beoordelen en bijeen te brengen van studies die programmatisch toetsen in het gezondheidszorgonderwijs in de praktijk onderzoeken. 

@schut2021rubber

### Theoretical considerations on programmatic assessment 

Dit artikel beschrijft opvallende theoretische perspectieven op programmatisch toetsen en er wordt onderzocht hoe theorie onderwijsprofessionals kan helpen effectieve programma's te ontwikkelen.

@torre2020theoretical

### Assessment and feedback in higher education reimagined: using programmatic assessment to transform higher education

In dit artikel worden de uitgangspunten va programmatisch toetsen beschreven en wordt een aantal handvatten gegeven voor opleidingen die willen starten met programmatisch toetsen.

@doi:10.1080/13603108.2023.2283118