---
title: "Praktijkvoorbeelden"
---

## ICT-systemen 

Het landelijk leernetwerk programmatisch toetsen organiseert driemaal per jaar webinars rondom een praktijkvraag gericht op programmatisch toetsen tijdens zogenoemde buitenkringbijeenkomsten. Tijdens de buitenkringbijeenkomst op 8 april 2022 werd stilgestaan bij de vraag aan welke eisen ICT-systemen moeten voldoen om de ontwikkeling van de studenten te kunnen monitoren en om zorgvuldige beslissingen over studenten te nemen. Je vindt hier zowel de opname als de materialen gebruikt tijdens de bijeenkomst. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/DTwiG0aquvE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

* [Powerpoint Buitenkring bijeenkomst 3](https://docs.google.com/presentation/d/13qCy-SsnRIobF6HgK8VibcREh5z_MTnG/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)
* [Hogeschool Inholland - Portfolio Mahara](https://docs.google.com/presentation/d/1qEyKHHGSAhOa4aZEpP_aN_uG6eWZXEkl/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)
* [Presentatie Arno Kamphuis - HU](https://docs.google.com/presentation/d/1kQOd_6HFYX2bqg-jpO7iUWzgWxd7Th2p/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)
* [Presentatie Hanneke Fens - HU](https://drive.google.com/file/d/1ObtPeecd3lWCvKHEehIeAPXD70C1fdIu/view?usp=share_link)

## Handreiking ontwerpeisen curriculum 

Fontys Paramedische Hogescholen maakte een handreiking die opleidingen kan ondersteunen bij het ontwerpen van het curriculum. In deze handreiking worden vijf ontwerpeisen toegelicht. In de ontwerpeis 'toetsconcept' wordt beschreven hoe bij het ontwerpen van het curriculum volgens de principes van programmatisch toetsen toetsing ingericht kan worden. 

[Handreiking Ontwerpeisen curriculumontwikkeling Fontys](https://drive.google.com/file/d/1UHDjq3bVNAhfma8okfa9wkv594C1TUug/view?usp=share_link)

## Profiel Fontys Paramedische Hogeschool

Binnen programmatisch toetsen vervult de docent meerdere rollen. Fontys Paramedische Hogeschool werkte de rollen voor hun docenten uit in deze profielschets. In deze beschrijving wordt onder meer ingegaan op het begeleiden van het leerproces van de studenten, het beoordelen en het beslissen.

[Profiel FPH docent Fontys Paramedische Hogeschool](https://drive.google.com/file/d/1bRJ7_0vvlgaU0QbNj8wbt0VVnhUW8lHJ/view?usp=sharing)

## Een curriculumperspectief op motivatie

Hoewel studenten het beste leren als ze er plezier in hebben of nieuwsgierig zijn, is de realiteit dat vele studenten in het hoger onderwijs vooral gefocust zijn op het halen van de toets. In [dit artikel](https://www.professioneelbegeleiden.nl/een-curriculumperspectief-op-motivatie) verklaren we deze focus middels een curriculumperspectief op motivatie. Dit perspectief levert concrete suggesties op voor het verbeteren van onze curricula.