---
title: "Praktische handvatten"
---

## Ontwerpprincipes inrichting studiecoaching 

Deze flyer geeft een overzicht van de belangrijkste ontwerprincipes voor het ontwerpen van de inrichting van de studiecoaching. De ontwerpprincipes kunen als handvat dienen bij zowel het gesprek over ontwerpkeuzes als bij het daadwerkelijke ontwerp.  

De ontwerpprincipes werden ontwikkeld door Debby Weerlink als onderdeel van haar masterproef voor de opleiding Master Toetsdeskundige. 

[Ontwerpprincipes inrichting studiecoaching](https://drive.google.com/file/d/1jD5OinQ3M25taTMn7reSwrUV5F4OUwh1/view?usp=share_link)

## Ontwerpvraagstukken 

Wil je als opleiding aan de slag met programmatisch toetsen? Dan zul je merken dat er verschillende ontwerpkeuzes gemaakt moeten worden. In dit artikel worden acht veelvoorkomende vraagstukken besproken en zijn gesprekskaarten gemaakt die helpen om deze vraagstukken gezamenlijk te bespreken. 

[Programmatisch toetsen: 8 dilemma's voor het ontwerp - Vernieuwenderwijs](https://www.vernieuwenderwijs.nl/programmatisch-toetsen-8-dilemmas/)

## Handreiking inrichting programmatisch toetsen (HU)

De Hogeschool Utrecht ontwikkelde een praktische handreiking voor opleidingen die willen gaan werken met de principes van programmatisch toetsen. In deze handreiking is er zowel aandacht voor het ontwikkelproces als voor de implementatie. 

## Ervaringen met programmatisch toetsen. Verslag van de themabijeenkomst

[Ervaringen met programmatisch toetsen: verslag van de themabijeenkomst](https://lerenvantoetsen.nl/ervaringen-met-programmatisch-toetsen-verslag-van-de-themabijeenkomst/)

## Ontwerptool medium stakes

In het leernetwerk programmatisch toetsen 2022-2023 zijn verschillende tools ontwikkeld die bruikbaar kunnen zijn voor opleidingen die programmatisch willen toetsen. Deze ontwerptool kun je gebruiken om samen medium-stakes beslissingen te ontwerpen in een opleiding waarin programmatisch wordt getoetst. Verschillende ontwerpvragen helpen je het gesprek hierover te voeren.  

[Ontwerptool documentatie](https://docs.google.com/document/d/1wwphFIJ-h8-poJZfVXiWYJFKB62o_8We/edit?usp=share_link&ouid=107473526964173779461&rtpof=true&sd=true)

[Ontwerptool invuldiagram](https://drive.google.com/file/d/16Zbb-0V9qmIp886CVcOlxRXmHK3XUEIk/view?usp=share_link)