---
title: "Meer weten?"
---

::: {.lead}

Er zijn meerdere (wetenschappelijke) artikelen verschenen over programmatisch toetsen waarbij ingegaan wordt op het ontwerpen van programmatisch toetsen. Onderstaande lijst geeft een overzicht.

:::

## Praktijkgerichte publicaties 

### Backwards design van een curriculum 

Een van de vragen die leeft bij opleidingen die (willen gaan) werken volgens de uitgangspunten van programmatisch toetsen is: ‘Hoe kom je tot een verantwoord en bewust samengesteld toetsprogramma?’. In dit artikel wordt een stappenplan geboden waarbij vanuit de te nemen beslissingen wordt toegewerkt naar het toetsprogramma.  

[Backwards design bij programmatisch toetsen](https://www.professioneelbegeleiden.nl/backward-design-bij-programmatisch-toetsen)

### Dashboard bij ontwikkelen van programmatisch toetsen 

In deze blog wordt een dashboard beschreven met succesfactoren voor de ontwikkeling van programmatisch toetsen.  

[Dashboard voor het ontwikkelen van programmatisch toetsen in je opleiding – Platform Leren van Toetsen](https://lerenvantoetsen.nl/dashboard-voor-het-ontwikkelen-van-programmatisch-toetsen-in-je-opleiding/)

### Ontwerpvraagstukken bij programmatisch toetsen 

In deze blog wordt stilgestaan bij drie ontwerpvraagstukken bij het ontwikkelen van een curriculum volgens de principes van programmatisch toetsen: feedbackproces, toetsprogramma en het nemen van beslissingen. De blog is gebaseerd op het wetenschappelijke artikel van Torre en collega's (2021). 

[Houvast bij het invoeren van programmatisch toetsen in de praktijk](https://lerenvantoetsen.nl/houvast-bij-het-invoeren-van-programmatisch-toetsen-in-de-praktijk/)

@torre2021ottawa

### Kennisclip over de ontwerpfunctie van programmatisch toetsen

<iframe width="560" height="315" src="https://www.youtube.com/embed/DM6IBCxWi5g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Kennisclip over de ontwerpprincipes voor studiecoaching bij programmatisch toetsen

In deze kennisclip gaat Debby Weerlink van Fontys in op de ontwerpprincipes voor studiecoaching bij programmatisch toetsen.

<iframe width="560" height="315" src="https://www.youtube.com/embed/VPXHVMCPUy4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Wetenschappelijke publicaties 

### Twelve Tips for programmatic assessment 

Dit artikel biedt twaalf concrete tips om programmatisch toetsen in de praktijk te ontwerpen. De auteurs hopen dat je hiermee zo ver als mogelijk kunt komen in jullie eigen praktijk. 

@doi:10.3109/0142159X.2014.973388

### Embedding of the progress test in an assessment program designed according to the principles of programmatic assessment 

Het inbedden van een voortgangstoets in een beoordelingsprogramma heeft een positieve invloed op de totale scores van die toets, gebruik van feedback uit die toets en waargenomen leerwaarde.

@doi:10.1080/0142159X.2016.1230183

### Development of a comprehensive clinical performance assessment system for nursing students: a programmatic approach 

Het doel van deze studie was om een uitgebreid beoordelingssysteem te ontwikkelen voor studenten verpleegkunde in hun intensive care stage op basis van een programmatische aanpak.

@imanipour2016development

### Designing programmes of assessment: a participatory approach 

De auteurs van dit artikel zien participatief actieonderzoek als een haalbare en effectieve manier voor het ontwerp van programmatisch toetsen. 

@jamieson2017designing