# Meer weten? 

Er zijn meerdere (wetenschappelijke) publicaties verschenen over programmatisch toetsen waarbij ingegaan wordt op het implementeren van programmatisch toetsen. Onderstaande lijst geeft een overzicht.  

## Praktijkgerichte publicaties 

### Voorwaarden voor programmatisch toetsen 

In [deze blog](https://lerenvantoetsen.nl/programmatisch-toetsen-in-het-hbo-dat-vraagt-moed/) wordt stilgestaan bij een viertal voorwaarden waaraan voldaan moet zijn om te kunnen starten met het ontwerpen en implementeren van programmatisch toetsen. 

### Programmatisch toetsen in verschillende onderwijsdomeinen 
Programmatisch toetsen wordt momenteel geïmplementeerd in verschillende onderwijsdomeinen. Liesbeth Baartman, Tamara van Schilt-Mol en Cees van der Vleuten legden een aantal implementaties naast elkaar om meer zicht te krijgen op de verschillen en overeenkomsten. Deze korte (Engelstalige) presentatie is opgenomen ten behoeve van het EARLI congres 2021. Zowel de opname als de gebruikte PowerPoint zijn hieronder te vinden. 

[Opname](https://drive.google.com/file/d/1pxVRoQYrRbHbd0pA0EIg11Iyh87eYnQn/view?usp=share_link)

[Powerpoint](https://drive.google.com/file/d/13YcT4IoY2c0TQvRuEKIViWdQlGJ2pGaN/view?usp=drive_link)

##  Buitenkringbijeenkomst 2 over 'Organisatieverandering bij programmatisch toetsen'

Marleen Kaaijen (HAN) en Fedde Kloppenburg (HU) geven in deze buitenkringbijeenkomst van het leernetwerk PT eerst inspiratie uit onderzoek en ervaringen over organisatieverandering bij programmatisch toetsen. Na 20 minuten wordt er verder gesproken in een panelgesprek onder begeleiding van Anke Swanenberg, Harry Rorije (HU) sluit daarbij aan.

[Opname](https://www.youtube.com/watch?v=OtOY-EJ_LA8&feature=youtu.be)

## Wetenschappelijke publicaties 

### Between trust and control: Teachers' assessment conceptualisations within programmatic assessment 

Dit artikel beschrijft een onderzoek hoe docenten beoordelingen conceptualiseren binnen programmatisch toetsen en hoe ze omgaan met studenten in beoordelingsrelaties. 

@schut2020between

### Ottawa 2020 consensus statements for programmatic assessment - 2. Implementation and 

Dit artikel beschrijft de implementatie van 12 principes van programmatisch toetsen en geeft inzicht in ondersteunende en belemmerende factoren. Het eerste deel van dit artikel staat in thema ‘basis’.

@torre2021ottawa

### Competency-based education calls for programmatic assessment: But what does this look like in practice? 

De bevindingen van dit onderzoek suggereren het belang van systeemdenken en de bijdrage van academische adviseurs bij het operationaliseren van programmatisch toetsen. 

@rich2020competency

### Thesis Teacher mindset and skills

Anne Hoogeveen onderzocht voor haar masterscriptie hoe docenten aankijken tegen programmatisch toetsen en over welke vaardigheden zij moeten beschikken. Haar (Engelstalige) scriptie is [hier](https://drive.google.com/file/d/1_M6w2kbKqlBPOeS7XSy1UjvSFLj4c1a2/view?usp=share_link) opgenomen.
