
# Praktische handvatten 

## Feedback geven 

Feedback is essentieel bij programmatisch toetsen. Het geven van goede feedback is echter niet eenvoudig, evenals het vragen van feedback. Fontys ontwikkelde handreikingen voor student, docent en werkveld over het geven en vragen van feedback.  

[Feedback handout Fontys](https://drive.google.com/file/d/1peI0cjEA9MMiMsX9CSbtIIy7AV78dnDr/view?usp=share_link) 

[Feedback handreiking docent Fontys](https://drive.google.com/file/d/1x06Wo8HGrejCqPsZaNnCNXNAVpfutOY-/view?usp=share_link)

[Feedback handreiking student Fontys](https://drive.google.com/file/d/1Mq7AOob2mjQyOjZnnj-liUUo5J2LFuiv/view?usp=share_link)

[Feedback handreiking werkveld Fontys](https://drive.google.com/file/d/1McdUHxbOoGFJFY9uNvpkmVWqKcSp-cwi/view?usp=share_link)

## Workshop feedback geven 

Instituut Archimedes (HU) ontwikkelde deze workshop die bestaat uit 2 delen. In deze workshop wordt expliciet stilgestaan bij feedback binnen de context van programmatisch toetsen. 

[Workshop feedback geven binnen programmatisch toetsen - Deel 1](https://docs.google.com/presentation/d/11XWjt4a1fH32iNk-BR-WWs6-yYzfyoQ8/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)

[Workshop feedback geven binnen programmatisch toetsen - Deel 2](https://docs.google.com/presentation/d/19TDY6MAmLPfdRR28hLIZJb_CYAd6QCKZ/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)

## Praatplaat grip op ontwikkeling 
  
Het is belangrijk om met studenten het gesprek aan te gaan over hun ontwikkeling. Deze praatplaat kan daarbij helpen. De praatplaat is door Lambert Zaad, Tugba Ozdes, Ria Kersbergen, Sabrina Bloemen en Ellen Leenaarts-Gunnewijk ontwikkeld in het HAN leernetwerk programmatisch toetsen (ontwerp: Studio Duikboot).  

[Praatplaat Grip op Ontwikkeling - Powerpoint HD, 1920x1080, 72ppi](https://drive.google.com/file/d/12fOtBBUUYFwm_HXdqsVWmIhIPwlkqAOP/view?usp=share_link)

[Praatplaat Grip op Ontwikkeling - A3, 4961x3508, 300ppi](https://drive.google.com/file/d/10FjLAUbJfzv96RVOEIBlXlDpBvR29E4v/view?usp=share_link)

[Grafiek uitgelicht - Print, 300ppi](https://drive.google.com/file/d/1clN596hZy9HAvrnfMk1ha610isClXSju/view?usp=share_link)

## Feedbackgids voor docenten en studenten

Katja van Zalen en Richard Kragten (Hogeschool van Amsterdam) hebben twee feedbackgidsen geschreven: één voor docenten en één voor studenten. De feedbackgids voor docenten is bedoeld om jou als docent te ondersteunen bij het inrichten van het feedbackproces in jouw onderwijs. Diverse workshops staan beschreven die als doel hebben de rol van studenten in het feedbackproces te vergroten. Ze dragen bij aan het meer feedbackgeletterd maken, zodat studenten zich ook bekwaam genoeg voelen om zich deze rol eigen te maken. De feedbackgids voor studenten is bedoeld om studenten te helpen bij het effectief gebruiken van feedback. Studenten hebben vaak moeite met het gebruikmaken van hun feedback en deze gids geeft daarvoor praktische tips.

[Feedbackgids voor docenten](https://drive.google.com/file/d/1gu7YeFCu3AagdDFa0wFWFtTpIuQSlrXT/view?usp=sharing)
[Feedbackgids voor studenten](https://drive.google.com/file/d/1OfZnodRju9e7PuNjvmxUyitvJSQiPwNG/view?usp=share_link)

## Saturatie: Weten waar je staat
Saturatie is een kernbegrip bij programmatisch toetsen, maar wel een lastig begrip voor studenten en begeleiders. Wat is saturatie eigenlijk? Studenten en begeleiders willen graag helderheid over het aantal datapunten dat in het portfolio “moet”. Daardoor stellen studenten vragen zoals: “doe ik wel de goede dingen bij het verzamelen van mijn datapunten?”, “neem ik wel de juiste informatie op in mijn portfolio?” en “heb ik wel genoeg informatie in mijn portfolio?” 
In het leernetwerk programmatisch toetsen 2022-2023 zijn daarom twee posters gemaakt. Eén poster bevat uitleg voor studenten over “weten waar je staat” bij programmatisch toetsen. De tweede poster is gebaseerd op het werk van Renske de Kleijn (2023) naar het stellen van feedbackvragen door studenten (bekijk voor meer informatie [dit webinar](https://lerenvantoetsen.nl/webinar-een-actieve-rol-van-de-student-in-het-feedbackproces/) voor het Platform Leren van Toetsen). Deze vragen zijn vertaald naar de context van programmatisch toetsen en vragen die studenten vaak stellen als het gaat om het vullen van hun portfolio met datapunten.

[Poster: Weten waar je staat](https://drive.google.com/file/d/1eLMh1xg_RtsX4Z6u97ASAeldjp5Zzcut/view?usp=share_link)
[Aanknopingspunten & valkuilen bij programmatisch toetsen](https://drive.google.com/file/d/14eCbhIJFIpo0xPvBziUQfL1JdjRdf7uz/view?usp=share_link)
