# Praktijkvoorbeelden 

## Het nemen van zorgvuldige beslissingen 

Het landelijk leernetwerk programmatisch toetsen organiseert driemaal per jaar webinars rondom een praktijkvraag gericht op programmatisch toetsen tijdens zogenoemde buitenkringbijeenkomsten. Tijdens de buitenkringbijeenkomst op 21 januari 2022 werd stilgestaan bij de vraag hoe zorgvuldige beslissingen over studenten genomen kunnen worden. Daarnaast werd stilgestaan bij het borgen van de kwaliteit van deze beslissingen. Je vindt hier zowel de opname als de materialen gebruikt tijdens de bijeenkomst. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/8gXmTCSaJBY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

[Buitenkring bijeenkomst 2: Presentatie](https://drive.google.com/file/d/1XCoA-PhkvyrNStBv6wP93GnK3s19HTNR/view?usp=share_link)

[Buitenkring bijeenkomst 2: Beslisprocedure](https://docs.google.com/presentation/d/1f1efBYfabum0xgJw_Hmp7-UzhH8EmJbg/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)

## Inrichten beslisprocedure 

Instituut Archimedes (HU) gebruikte de [gesprekskaartjes](https://docs.google.com/presentation/d/1hbygrJ1ITpJGOOgGNuD0FW7pc5HZXY91/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true) die ontwikkeld zijn in het landelijk leernetwerk programmatisch toetsen om een procedure uit te werken voor het komen tot een high stake beslissing. Deze procedure is als praktijkvoorbeeld toegevoegd. 

[Procedure high-stake beslissingen van de HU](https://docs.google.com/document/d/1pzVYz8-Cy9CoHyCqXOu3HJ7bCf3I7fqH/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)