# Praktische handvatten 

## Inrichten van de beslisprocedure 

Hoe richt je de beslisprocedure in? Wil je hierover samen met collega's in gesprek, dan bieden deze gesprekskaartjes een mooi handvat om dat gesprek te voeren. De gesprekskaartjes werden ontwikkeld door Maartjes de Groot, Jantina Huizenga en Judith Revet in het landelijk leernetwerk programmatisch toetsen. 

[Gesprekskaartjes beslisproces](https://docs.google.com/presentation/d/1hbygrJ1ITpJGOOgGNuD0FW7pc5HZXY91/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)

## Ontwerptool medium stakes

In het leernetwerk programmatisch toetsen 2022-2023 zijn verschillende tools ontwikkeld die bruikbaar kunnen zijn voor opleidingen die programmatisch willen toetsen. Deze ontwerptool kun je gebruiken om samen medium-stakes beslissingen te ontwerpen in een opleiding waarin programmatisch wordt getoetst. Verschillende ontwerpvragen helpen je het gesprek hierover te voeren.  

[Ontwerptool documentatie](https://docs.google.com/document/d/1wwphFIJ-h8-poJZfVXiWYJFKB62o_8We/edit?usp=share_link&ouid=107473526964173779461&rtpof=true&sd=true)

[Ontwerptool invuldiagram](https://drive.google.com/file/d/16Zbb-0V9qmIp886CVcOlxRXmHK3XUEIk/view?usp=share_link)