# Praktische handvatten 

## Gesprekstool kwaliteitsborging examinatoren bij programmatisch toetsen  

Veel examencommissies zoeken hoe zij de kwaliteit van examinatoren bij opleidingen die programmatisch toetsen kunnen borgen. De gesprekstool kwaliteitsborging examinatoren bij programmatisch toetsen, die bestaat uit gesprekskaarten over verschillende onderwerpen, kan examencommissies ondersteunen in het maken van keuzes. Het doel van de gesprekstool is enerzijds examencommissies inzicht te geven in mogelijke dilemma’s ten aanzien van de kwaliteitsborging van de examinator bij PT, en anderzijds de dialoog te faciliteren om tot doordachte keuzes te komen binnen de ruimte die de kaders bieden.  

[Gesprekstool kwaliteitsborging examinatoren bij programmatisch toetsen](https://drive.google.com/file/d/10juwQ0TBNENqnTCYMDqLFwkOZSXYb6W_/view?usp=share_link)

## De rol van de examencommissie - hoe 

Hoe kunnen examencommissies op een goede manier invulling geven aan hun wettelijke taak (het borgen van de kwaliteit van toetsing) bij opleidingen die werken volgens de principes van programmatisch toetsen? In dit tweeluik wordt eerst ingegaan op de rol van de examencommissie, daarna op concrete instrumenten waarmee de examencommissie invulling kan deze aan deze rol. Deel 1 van dit tweeluik is te vinden bij de praktijkgerichte publicaties op deze pagina. 

[Holistisch beslissen en de borging van kwaliteit door een examencommissie, hoe dan?](https://lerenvantoetsen.nl/holistisch-beslissen-en-de-borging-van-kwaliteit-door-een-examencommissie-hoe-dan/)

## De rol van de examencommissie bij programmatisch toetsen

[Naar gecontroleerd vertrouwen. De rol van de examencommissie bij programmatisch toetsen](https://lerenvantoetsen.nl/naar-gecontroleerd-vertrouwen-de-rol-van-de-examencommissie-bij-programmatisch-toetsen/)

## Protocol toetsing en beoordeling bij de huisartsenopleiding 

In de huisartsenopleiding wordt gewerkt volgens de principes van programmatisch toetsen. Op deze site staan het toetsplan en het 'protocol toetsing en beoordeling' dat de opleiding hanteert. Hierin is uitgewerkt hoe de ontwikkeling van de student gedurende de opleiding steeds onderwerp van gesprek is en hoe (en op basis waarvan) beslissingen worden genomen. 

[Huisartsenopleiding: Programmatisch toetsen](https://www.huisartsopleiding.nl/toetsen-beoordelen/programmatisch-toetsen/)

## Zelfevaluatie kwaliteit van toetsprogramma 

De zelfevaluatie-methodiek KIT2.0 is gebaseerd op principes van programmatisch toetsen. Deze basisprincipes zie je terug in de kwaliteitscriteria. Met de methodiek kun je de kwaliteit van je toetsprogramma in kaart brengen en nagaan hoe je toetsprogramma zich verhoudt tot de uitgangspunten van programmatisch toetsen. 

[Kwaliteitsinstrument Toetsprogramma (kwaliteit-toetsprogramma.nl)](https://www.kwaliteit-toetsprogramma.nl/)

## Checklists beslisfunctie en programma van datapunten

Deze checklist is een hulpmiddel voor examencommissies (en toetscommissies) om de highstakebeslissingen bij programmatisch toetsen te borgen. Met behulp van de checklist kan de examencommissie de beslisfunctie van programmatisch toetsen, zoals dat binnen een opleiding is vormgegeven, in kaart brengen.

[checklist beslisfunctie en programma van datapunten](https://drive.google.com/file/d/1cWB4SFt_i_EkpxYUM70Q6mGQuIfbl_f0/view?usp=sharing)