# Praktijkvoorbeelden 

## Het borgen van de kwaliteit van zorgvuldige beslissingen 

Het landelijk leernetwerk programmatisch toetsen organiseert driemaal per jaar webinars rondom een praktijkvraag gericht op programmatisch toetsen tijdens zogenoemde buitenkringbijeenkomsten. Tijdens de buitenkringbijeenkomst op 21 januari 2022 werd stilgestaan bij de vraag hoe zorgvuldige beslissingen over studenten genomen kunnen worden. Daarnaast werd stilgestaan bij het borgen van de kwaliteit van deze beslissingen. Je vind hier zowel de opname als de materialen gebruikt tijdens de bijeenkomst. 

[Buitenkring bijeenkomst 2: Opname](./bronnen/56_Buitenkring_Bijeenkomst2_Opname.mp4)

[Buitenkring bijeenkomst 2: Presentatie](https://drive.google.com/file/d/1XCoA-PhkvyrNStBv6wP93GnK3s19HTNR/view?usp=share_link)

[Buitenkring bijeenkomst 2: Beslisprocedure](https://docs.google.com/presentation/d/1f1efBYfabum0xgJw_Hmp7-UzhH8EmJbg/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true)

## Toetsplan definitief vakdidactisch handelen 

Het [toetsplan 'vakdidactisch handelen: ontwerpen van onderwijs'](https://docs.google.com/document/d/1yra-6ByIKWyZ0Mj4mwx7H-MxQrtZHeqe/edit?usp=share_link&ouid=113832975952028051169&rtpof=true&sd=true) van Instituut Archimedes van de Hogeschool Utrecht geeft een voorbeeld van hoe de principes van programmatisch toetsen verwerkt zijn in een toetsplan.
