# Meer weten? 

Er zijn meerdere (wetenschappelijke) artikelen verschenen over programmatisch toetsen waarbij ingegaan wordt op het zorgen voor en borgen van de kwaliteit van toetsing bij programmatisch toetsen. Onderstaande lijst geeft een overzicht.  

## Wetenschappelijke publicaties 

### Programmatic assessment: Can we provide evidence for saturation of information?

De auteurs willen valide bewijs leveren voor saturatie van informatie door onderzoek naar de relatie tussen aantal datapunten dat de minimumeis overschrijdt en consensus tussen twee beoordelaars.

@doi:10.1080/0142159X.2018.1555369

### The pursuit of fairness in assessment: Looking beyond the objective 

De auteurs onderzoeken eerlijkheid als een fundamentele kwaliteit van beoordelingen. Deze benadering legitimeert menselijk oordeel en gedeelde subjectiviteit in beslissingen naast objectieve methoden.

@valentine2022pursuit

## Praktijkgerichte publicaties 

### Kennisclips zorgen en borgen 

In zeven korte kennisclips wordt ingegaan op het zorgen voor en borgen van kwaliteit voor toetsing binnen de context van programmatisch toetsen. De kennisclips zijn gemaakt door Sylvia Heeneman en Irene Biemond.  

**Kennisclip 1 - Inleiding en samenvatting**

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZfU9PxoqG2A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Kennisclip 2 - Toetsbeleid**

<iframe width="560" height="315" src="https://www.youtube.com/embed/BRCAits1gmI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Kennisclip 3 - Overzicht van datapunten**

<iframe width="560" height="315" src="https://www.youtube.com/embed/9H7eVuNzCR4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Kennisclip 4 - Highstake beslissing**

<iframe width="560" height="315" src="https://www.youtube.com/embed/VdWTBymux9s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Kennisclip 5 - Datapunten**

<iframe width="560" height="315" src="https://www.youtube.com/embed/q7UTJJS4GI8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Kennisclip 6 - Toetsorganisatie**

<iframe width="560" height="315" src="https://www.youtube.com/embed/cwmR2-_YEDI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Kennisclip 7 - Toetsbekwaamheid**

<iframe width="560" height="315" src="https://www.youtube.com/embed/5c3P3ecE7wQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>