---
title: "Praktijkvoorbeelden"
---

::: {.lead}

Hieronder staat het overzicht van 19 portretten zoals gepubliceerd op het platform Leren van Toetsen. 

:::

## Hogeschool van Arnhem en Nijmegen: opleiding Mondzorgkunde

Als je belangrijke beslissingen neemt over studenten zoals het toekennen van (grote aantallen) studiepunten, wat uiteindelijk zal leiden tot het toekennen van een diploma, dan is het belangrijk dat deze beslissing betrouwbaar en valide is.  

[Hogeschool van Arnhem en Nijmegen: opleiding Mondzorgkunde](https://lerenvantoetsen.nl/praktijkvoorbeelden/hogeschool-van-arnhem-en-nijmegen-opleiding-mondzorgkunde/)

## Avans hogeschool: Business Innovation (2021 – 2022)

Sinds september 2021 is de bacheloropleiding Business Innovation aan de Avans Hogeschool gestart met het implementeren van programmatisch toetsen in het propedeusejaar. Hierbij gaat het om drie onderwijseenheden (modules) van elk 11 EC. Momenteel is de opleiding bezig met herontwikkeling per jaar om zo de gehele opleiding programmatisch in te richten. De focus van dit portret ligt op het programmatisch toetsen in het propedeusejaar en is een momentopname van mei 2022.

[Avans hogeschool: Business Innovation](https://lerenvantoetsen.nl/avans-hogeschool-business-innovation-2021-2022/)

## Hogeschool van Amsterdam: opleiding Voeding & Diëtetiek (2021 – 2022)

Studenten van de bacheloropleiding Voeding & Diëtetiek aan de Hogeschool van Amsterdam worden opgeleid tot voedingsprofessionals. De gehele opleiding telt 800-900 studenten. De opleiding is in 2020 gestart met het implementeren van programmatisch toetsen in ongeveer de helft van het eerste jaar. De opleiding is momenteel bezig om stap voor stap programmatisch toetsen ook in de andere leerjaren te implementeren. In dit portret lees je meer over ontwerpkeuzes en de implementatie van programmatisch toetsen in de hoofdfase (jaar 2 en 3, 90 EC) van de opleiding.

[Hogeschool van Amsterdam: opleiding Voeding & Diëtetiek](https://lerenvantoetsen.nl/hva-voeding-dietetiek-2021-2022/)

## HAN: Sportkunde en ALO – voortbouwen op talenten om te komen tot een eigen visitekaartje

De afstudeerfase (60 EC) van de opleidingen Algemene Lichamelijke Opvoeding (ALO) en Sportkunde van de HAN zijn programmatisch ingericht. In september 2020 is de opleiding Sportkunde begonnen en september 2021 is ook de ALO gestart. Dit portret is een momentopname van begin 2022.

[HAN: Sportkunde en ALO](https://lerenvantoetsen.nl/han-alo-sportkunde/)

## Fontys Hogescholen: Bachelor Communicatie – International Event Music and Entertainment Studies (IEMES)

De bacheloropleiding Communicatie International Event Music and Entertainment Studies (CO IEMES) van Fontys bestaat uit ongeveer 650-700 studenten. De opleiding is in 2018 gestart met het implementeren van programmatisch toetsen in jaar 2. Inmiddels wordt programmatisch toetsen binnen de gehele opleiding toegepast. Lees hier meer over hoe zij dit hebben aangepakt en waar zij staan in dit proces begin 2022.

[Fontys Hogescholen: IEMES](https://lerenvantoetsen.nl/fontys-iemes/)

## Hogeschool Saxion: opleiding Bedrijfskunde (2021 – 2022)

De bacheloropleiding Bedrijfskunde van de Saxion Hogeschool is in februari 2022 gestart met een pilot (30 voltijdstudenten) voor programmatisch toetsen in het eerste jaar. Hetgeen geleerd is tijdens de pilot, heeft de opleiding meegenomen bij het implementeren van programmatisch toetsen in studiejaar 2022-2023, waarbij programmatisch toetsen in de gehele opleiding wordt ingezet. De ervaringen met de pilot en de implementatie van programmatisch toetsen in het gehele programma worden gedeeld in dit portret.

[Hogeschool Saxion: opleiding Bedrijfskunde](https://lerenvantoetsen.nl/hogeschool-saxion-opleiding-bedrijfskunde-2021-2022/)

## Hogeschool Windesheim: Opleiding Oefentherapie – programmatisch toetsen ontwerpen voor een nieuwe opleiding (2022)

Aan Hogeschool Windesheim is de opleiding Oefentherapie nieuw gestart in september 2022. De opleiding bestaat al wel bij Hogeschool Utrecht en de Hogeschool van Amsterdam. Echter is het laatste cohort bij de Hogeschool Utrecht in september 2021 gestart en in Amsterdam verandert de opleiding waarbij studenten breder starten en oefentherapie een uitstroomrichting is. Oefentherapie aan de Hogeschool Windesheim is echt een aparte opleiding gericht op oefentherapie. Oefentherapie is een vak waarin heel holistisch gekeken wordt naar de mens. De opleiding wil studenten leren om holistisch naar de mens te kijken en wil zelf dan ook zo naar studenten kijken. Vanuit die visie heeft de opleiding gekozen voor programmatisch toetsen. Oefentherapie is een nieuwe opleiding, waardoor het ontwikkelteam de opleiding volledig vanuit deze visie kon gaan vormgeven.

[Hogeschool Windesheim: Opleiding Oefentherapie](https://lerenvantoetsen.nl/hogeschool-windesheim-opleiding-oefentherapie-programmatisch-toetsen-ontwerpen-voor-een-nieuwe-opleiding/)

## Hogeschool Utrecht: Opleiding Communicatie – als opleiding ingroeien in programmatisch toetsen (2022)

De bacheloropleiding Communicatie aan de Hogeschool Utrecht heeft al de nodige ervaring met programmatisch toetsen: in 2017 zijn ze gestart met het implementeren van programmatisch toetsen in het tweede leerjaar en ondertussen wordt in de gehele opleiding programmatisch getoetst. Elk jaar beginnen tussen de 150 en 200 nieuwe studenten aan de opleiding met in totaal ongeveer 600 a 700 studenten. In dit portret lees je hoe ze gaandeweg zijn ingegroeid in het werken met programmatisch toetsen.

[Hogeschool Utrecht: Opleiding Communicatie](https://lerenvantoetsen.nl/hogeschool-utrecht-opleiding-communicatie-als-opleiding-ingroeien-in-programmatisch-toetsen-2022/)

## HAS Toegepaste Biologie: ambitieuze plannen voor programmatisch toetsen (2021)

De opleiding Toegepaste Biologie heeft het ontwerpen van programmatisch toetsen serieus aangepakt en hebben de tijd genomen om tot een gedegen ontwerp te komen. Ze zijn begonnen met het formuleren van de leeruitkomsten, hebben vervolgens de datapunten en het bijbehorende onderwijs uitgewerkt, en zich daarna op de beslisprocedure gericht. In september 2022 is de opleiding van start gegaan met programmatisch toetsen vanaf het eerste leerjaar terwijl het ontwerpproces voor de andere leerjaren doorloopt. In dit portret lees je meet over de aanpak van Toegepaste Biologie van HAS Green academy.

[HAS Toegepaste Biologie](https://lerenvantoetsen.nl/has_toegepaste_biologie/)

## Hogeschool van Amsterdam: Educatief Professional Beroepsonderwijs (AD) – programmatisch toetsen met veel flexibiliteit (2022)

De opleiding Educatief Professional Beroepsonderwijs is een kleine associate degree (AD) opleiding. Er zitten in het studiejaar 2021-2022 vier studenten in het eerste leerjaar en twaalf studenten in het tweede leerjaar. De opleiding wil inzetten op langdurige ontwikkeling en veel flexibiliteit voor de studenten. In dit portret lees je hoe ze programmatisch toetsen gebruiken om deze doelstellingen te bereiken.

[Hogeschool van Amsterdam: Educatief Professional Beroepsonderwijs (AD)](https://lerenvantoetsen.nl/hogeschool-van-amsterdam-educatief-professional-beroepsonderwijs-ad-programmatisch-toetsen-met-veel-flexibiliteit-2022/)

## Hogeschool Arnhem en Nijmegen: opleiding Voeding en Diëtetiek (2020 – 2021)

De voltijdopleiding Voeding en Diëtetiek van de Hogeschool Arnhem en Nijmegen is een vierjarige hbo-opleiding met +/- 600 studenten. Vanaf studiejaar 2019-2020 heeft de opleiding een deel van het propedeusejaar en een deel van het tweede jaar programmatisch ingericht. Stapsgewijs wil de opleiding in studiejaar 2021-2022 programmatisch toetsen in de gehele opleiding inzetten. Dit portret is een momentopname van juli 2021.

[Hogeschool Arnhem en Nijmegen: opleiding Voeding en Diëtetiek](https://lerenvantoetsen.nl/praktijkvoorbeelden/han-voeding-dietetiek/)

## Hogeschool Utrecht: minor Leefstijl Coaching (2021-2022)

Op de Hogeschool van Utrecht kunnen studenten de minor Leefstijl Coaching volgen. Deze minor heeft een omvang van 30 EC, duurt een half jaar en is voor zowel voltijd- als deeltijdstudenten. De minor telt +/- 30 studenten. Een deel van de minor (20 EC) is programmatisch ingericht. Dit portret is een momentopname van begin 2022.

[Hogeschool Utrecht: minor Leefstijl Coaching](https://lerenvantoetsen.nl/praktijkvoorbeelden/hogeschool-utrecht-minor-leefstijl-coaching-2021-2022/)

## Fontys ICT: programmatisch toetsen in het eerste semester van de propedeuse (2020 – 2021)

De opleiding ICT aan Fontys Hogeschool is toegankelijk voor Nederlandse en internationale studenten en biedt verschillende leervormen om kennis en vaardigheden op te doen. In het allereerste semester van de course-based leervorm wordt gewerkt volgens de uitgangspunten van programmatisch toetsen. De opleiding beoordeelt studenten op het geheel van wat ze kunnen in plaats van naar losse modules te kijken.

[Fontys ICT: propedeuse](https://lerenvantoetsen.nl/praktijkvoorbeelden/aeres-2/)

## Aeres Hogeschool: opleiding Food Systems Innovation (2020-2021)

Food Systems Innovation is een Engelstalige éénjarige masteropleiding van 60 EC aan Aeres Hogeschool met een instroom van 15 á 20 studenten per jaar. In de visie van de opleiding staat ontwikkelingsgericht opleiden centraal, waarbij studenten constant werken aan de vijf eindkwalificaties van de opleiding en zo professionals worden die geleerd hebben zich continu te ontwikkelen. De opleiding kent drie onderwijsperiodes die ieder bestaan uit twee onderwijsmodules. De opleiding Food Systems Innovations is per september 2021 gestart met het implementeren van programmatisch toetsen. In dit profiel lees je hoe ze dit aanpakken.

[Aeres Hogeschool: opleiding Food Systems Innovation](https://lerenvantoetsen.nl/praktijkvoorbeelden/aeres/)

## Marnix Academie: het inzetten van programmatisch toetsen voor het opleiden van zelfregulerende onderwijsprofessionals (2022)

De Marnix Academie (Pabo Utrecht) is een voltijd bachelor opleiding met een totale studielast van 240 ECT. De opleiding is in september 2021 voor het nieuwe cohort gestart met een nieuw curriculum waarbij voor programmatisch toetsen is gekozen. Het gaat hierbij om zo’n 250 studenten. Dit portret is een momentopname van begin 2022.

[Marnix Academie: onderwijsprofessionals](https://lerenvantoetsen.nl/praktijkvoorbeelden/marnix/)

## Hogeschool Arnhem en Nijmegen: Master Ontwerpen van Eigentijds Leren (2020-2021)

De deeltijd masteropleiding ontwerpen van eigentijds leren (MOVEL) van de Hogeschool van Arnhem en Nijmegen (HAN) is een tweejarige masteropleiding met een totale studiebelasting van 60 ECT. Studenten hebben 1 dag per week een bijeenkomst, verder ontwikkelen zij zich op de werkplek en werken zij samen in de online leeromgeving. De opleiding is gestart in september 2019 met ongeveer 20 studenten; in 2021 zijn er ongeveer 50 studenten gestart. In dit portret wordt uitgelegd hoe zij werken volgens de principes van programmatisch toetsen.

[Hogeschool Arnhem en Nijmegen: Master Ontwerpen van Eigentijds Leren](https://lerenvantoetsen.nl/praktijkvoorbeelden/han-movel/)

## Hogeschool van Amsterdam: HBO ICT (2021)

HBO ICT wil uiteindelijk de hele bachelor ICT richting programmatisch toetsen (als onderdeel van een onderwijsvernieuwing), maar dit wordt gefaseerd uitgerold, beginnend bij het 3e leerjaar van de leerroute Business IT & Management. In februari 2021 is binnen deze leerroute voor het eerst gestart met programmatisch toetsen. Naast deze leerroute wordt in dit portret ook ingegaan op een experiment bij de leerroute Game Development.

[Hogeschool van Amsterdam: HBO ICT](https://lerenvantoetsen.nl/praktijkvoorbeelden/hogeschool-van-amsterdam_hbo-ict/)

## Fontys Paramedische Hogeschool: een omvangrijk ontwerp en implementatieproces (2020-2021)

Fontys Paramedische Hogeschool (FPH) startte in september 2021 met programmatisch toetsen in de afstudeerfase van 5 bacheloropleidingen: een omvangrijk ontwerp en implementatieproces. De FPH visie op leren gaat uit van de lerende aan het stuur, leren vanuit een uitdagende, authentieke beroepscontext en het geleerde integraal toepassen in de praktijk. In dit portret vertellen ze meer over hun gekozen aanpak.

[Fontys Paramedische Hogeschool](https://lerenvantoetsen.nl/praktijkvoorbeelden/fontys-paramedische-hogeschool-een-omvangrijk-ontwerp-en-implementatieproces-2020-2021/)

## Hogeschool Inholland: opleiding Pedagogiek (2020-2021)

De bacheloropleiding Pedagogiek van hogeschool Inholland bestaat uit ongeveer 500 tot 550 voltijd studenten. De opleiding is per 1 september 2021 begonnen met het implementeren van programmatisch toetsen voor leerjaar 1 en 2 per nieuw cohort. In dit portret vertellen zij hoe zij dit hebben aangepakt.

[Hogeschool Inholland: opleiding Pedagogiek](https://lerenvantoetsen.nl/praktijkvoorbeelden/hogeschool-inholland-opleiding-pedagogiek-2020-2021/)