project:
  type: website
  output-dir: docs

website:
  title: "Leeromgeving programmatisch toetsen"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      # - text: Hoofdstukken
      - text: "Basis"
        file: 1-basis.qmd
      - text: "Ontwerpvraagstuk"
        file: 2-ontwerpvraagstuk.qmd
      - text: "Implementeren"
        file: 3-implementeren.qmd
      - text: "Leerfunctie"
        file: 4-leerfunctie.qmd
      - text: "Besisfunctie"
        file: 5-beslisfunctie.qmd
      - text: "Zorgen en borgen"
        file: 6-zorgen_borgen.qmd
      #   menu:
      #     - sidebar:modules      
      - about.qmd
      
  sidebar:
    - id: modules
      title: "Hoofdstukken"
      style: "docked"
      # foreground: '#BC0031'
      background: light
      collapse-level: 2
      contents:
        - 1-basis.qmd
        - 2-ontwerpvraagstuk.qmd
        - 3-implementeren.qmd
        - 4-leerfunctie.qmd
        - 5-beslisfunctie.qmd
        - 6-zorgen_borgen.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    bibliography: references.bib



